# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Api to Azure Web App

on:
  workflow_run:
    workflows: [Test Project]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read #This is required for actions/checkout
      id-token: write #This is required for requesting the JWT
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      
      - name: dotnet publish
        run: |
          cd Consilium/Consilium.API
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1B3A1238CCB24F959EBD3F744CEEB3B3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_435D1B6923F44B4E82FA646F8FCEC59F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7D5EEDC437EB451F9826076F416E790C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'consilium-api'
          slot-name: 'Production'
          package: .
          